### ISSUE TITLE
Where can i get the camera Intrinsics ？

### ISSUE THREAD

**Issue by liaoksn** [3dlg-hcvc/OPD#6]
Thanks for sharing this job. I'm wondering where can i get the camera intrisics of the depth camera and rgb camera ?

**Comment by Jianghanxiao** [comment]
Hi, thanks for asking. Do you mean where you can get the camera intrinsic from our dataset or from your data?

The camera intrinsic is the attributes of your camera. In theory, you need to check your camera to get relevant parameters. 

For our dataset, we store the intrinsic parameters for the images in the coco annotation file. And because we use the same camera for the dataset, actually the intrinsic for different images is nearly the same, in the code, when visualization, we hard-code the intrinsic into the visualization code.
