### ISSUE TITLE
Is object pose given in the dataset?

### ISSUE THREAD

**Issue by ahnaf1393** [3dlg-hcvc/OPD#8]
Hello, 
Thank you for sharing the code and dataset of your work. Do you provide the pose of the objects in your dataset? I saw that in your OPDMulti dataset, the abs_pose is included there. How can I get the pose for this case?

**Comment by Jianghanxiao** [comment]
Hi,
Thanks for asking. Yes, we prove the pose of the objects in our dataset. Because the OPDSynth and OPDReal dataset focus on a single object, the camera extrinsic here can be treated as the object pose. The OPDRCNN code also leverages the same logic. You can check the dataloader on how the extrinsic parameters are read and used

**Comment by ahnaf1393** [comment]
Thank you for your reply. I am closing the issue now.
